require 'minitest/autorun'
require 'minitest/pride'
require 'terminal-table'
require 'pry'

require './lib/flight'
require './lib/duration'
require './lib/airport1'
require './lib/earth'
require './lib/point'
require './lib/plane'
require './lib/report'